# Change these first
owner: Baronhez # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Personal WebPage
    url: https://jonthan.xyz
  - name: Filebrowser in Server
    url: https://files.jonthan.xyz
  - name: Bookmark Manager
    url: https://linkding.jonthan.xyz
  - name: Dashboard Server
    url: https://flame.jonthan.xyz
  - name: Dashboard Home Server
    url: https://server.jonthan.xyz
  - name: Internet Speed in my server
    url: https://speed.jonthan.xyz
  - name: Torrent webUI
    url: https://torrent.jonthan.xyz
  - name: Actual
    url: https://actual.jonthan.xyz
 
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Baronhez Status Page
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This webpage is powered by this [GitHub repository](https://github.com/upptime/upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
